name: 'Tweet action'
description: 'Tweet in Twitter via GitHub Actions'
author: 'doomspec'
inputs:
  text:
    required: true
    description: 'The text of the status update. URL encode as necessary. t.co link wrapping will affect character counts.'
outputs:
  response:
    description: 'Response JSON'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'edit'
  color: 'blue'